language: csharp  
solution: RSOIlab1.sln
mono: none
dotnet: 2.1.300
install:
  - dotnet restore
script:
  - dotnet publish ./RSOIlab1/RSOIlab1.csproj
  - dotnet test ./Tests/Tests.csproj
 deploy:
  provider: heroku
  app: milarsoi
  api_key: 37396626-d2ab-428b-baa0-acb5471d806d
